AUDIO_PATH = "/home/pi/ftp/files/R2/"
AUDIO_VOLUME = 1.0
AUTO_CATEGORY = "music"
AUTO_INTERVAL = 60
LOG_LEVEL = "DEBUG"

PERISCOPE_MOTOR = "A"
PERISCOPE_DEGREES = 850
PERISCOPE_DEGREES_MAXIMUM = PERISCOPE_DEGREES
PERISCOPE_DEGREES_MINIMUM = 15
PERISCOPE_THRESHOLD = 700
PERISCOPE_SPEED = 25

ROTATION_MOTOR = "B"
ROTATION_INVERT = True
ROTATION_THRESHOLD = 10
