AUDIO_PATH = "./assets/"
AUDIO_VOLUME = 1.0

AUTO_CATEGORY = "misc"
AUTO_INTERVAL = 5

LOG_LEVEL = "DEBUG"

PERISCOPE_LED = 21

ARM_ENABLED = True
ARM_MOTOR = "A"
ARM_DEGREES_OPEN = -100
ARM_DEGREES_CLOSE = 120
ARM_SPEED = 5

ROTATION_ENABLED = True
ROTATION_MOTOR = "B"
ROTATION_INVERT = True
ROTATION_THRESHOLD = 10

DOOR_LEFT_ENABLED = True
DOOR_LEFT_MOTOR = "C"
DOOR_LEFT_DEGREES_OPEN = 90
DOOR_LEFT_DEGREES_CLOSE = -90
DOOR_LEFT_SPEED = 5

DOOR_RIGHT_ENABLED = True
DOOR_RIGHT_MOTOR = "D"
DOOR_RIGHT_DEGREES_OPEN = -90
DOOR_RIGHT_DEGREES_CLOSE = 90
DOOR_RIGHT_SPEED = 5

TRACK_ENABLED = True
TRACK_MAX_SPEED = 20000
TRACK_TTY_LEFT = '/dev/ttyACM1'
TRACK_TTY_RIGHT = '/dev/ttyACM0'