AUDIO_PATH = "/home/pi/ftp/files/R2/"
AUDIO_VOLUME = 1.0
AUTO_CATEGORY = "music"
AUTO_INTERVAL = 60
LOG_LEVEL = "DEBUG"

PERISCOPE_MOTOR = "A"
PERISCOPE_DEGREES = 720
PERISCOPE_THRESHOLD = 700
PERISCOPE_SPEED = 25

ROTATION_MOTOR = "B"
ROTATION_THRESHOLD = 10
